<?php

namespace Container6RLptQf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PbYvu3OService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PbYvu3O' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PbYvu3O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Authentication\\Controller\\SecurityController::login' => ['privates', '.service_locator.0zSEwe3', 'get_ServiceLocator_0zSEwe3Service', true],
            'App\\Authentication\\Controller\\SecurityController::nativeAuthLogin' => ['privates', '.service_locator.0zSEwe3', 'get_ServiceLocator_0zSEwe3Service', true],
            'App\\Authentication\\Controller\\SecurityController::nativeAuthSessionStatus' => ['privates', '.service_locator.XOxzSlt', 'get_ServiceLocator_XOxzSltService', true],
            'App\\Authentication\\Controller\\SecurityController::sessionStatus' => ['privates', '.service_locator.XOxzSlt', 'get_ServiceLocator_XOxzSltService', true],
            'App\\Engine\\Controller\\IndexController::index' => ['privates', '.service_locator.XOxzSlt', 'get_ServiceLocator_XOxzSltService', true],
            'App\\Engine\\Controller\\IndexController::loggedOut' => ['privates', '.service_locator.dbFJ5zg', 'get_ServiceLocator_DbFJ5zgService', true],
            'App\\Engine\\Controller\\IndexController::nativeAuth' => ['privates', '.service_locator.XOxzSlt', 'get_ServiceLocator_XOxzSltService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Authentication\\Controller\\SecurityController:login' => ['privates', '.service_locator.0zSEwe3', 'get_ServiceLocator_0zSEwe3Service', true],
            'App\\Authentication\\Controller\\SecurityController:nativeAuthLogin' => ['privates', '.service_locator.0zSEwe3', 'get_ServiceLocator_0zSEwe3Service', true],
            'App\\Authentication\\Controller\\SecurityController:nativeAuthSessionStatus' => ['privates', '.service_locator.XOxzSlt', 'get_ServiceLocator_XOxzSltService', true],
            'App\\Authentication\\Controller\\SecurityController:sessionStatus' => ['privates', '.service_locator.XOxzSlt', 'get_ServiceLocator_XOxzSltService', true],
            'App\\Engine\\Controller\\IndexController:index' => ['privates', '.service_locator.XOxzSlt', 'get_ServiceLocator_XOxzSltService', true],
            'App\\Engine\\Controller\\IndexController:loggedOut' => ['privates', '.service_locator.dbFJ5zg', 'get_ServiceLocator_DbFJ5zgService', true],
            'App\\Engine\\Controller\\IndexController:nativeAuth' => ['privates', '.service_locator.XOxzSlt', 'get_ServiceLocator_XOxzSltService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Authentication\\Controller\\SecurityController::login' => '?',
            'App\\Authentication\\Controller\\SecurityController::nativeAuthLogin' => '?',
            'App\\Authentication\\Controller\\SecurityController::nativeAuthSessionStatus' => '?',
            'App\\Authentication\\Controller\\SecurityController::sessionStatus' => '?',
            'App\\Engine\\Controller\\IndexController::index' => '?',
            'App\\Engine\\Controller\\IndexController::loggedOut' => '?',
            'App\\Engine\\Controller\\IndexController::nativeAuth' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Authentication\\Controller\\SecurityController:login' => '?',
            'App\\Authentication\\Controller\\SecurityController:nativeAuthLogin' => '?',
            'App\\Authentication\\Controller\\SecurityController:nativeAuthSessionStatus' => '?',
            'App\\Authentication\\Controller\\SecurityController:sessionStatus' => '?',
            'App\\Engine\\Controller\\IndexController:index' => '?',
            'App\\Engine\\Controller\\IndexController:loggedOut' => '?',
            'App\\Engine\\Controller\\IndexController:nativeAuth' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
