<?php

namespace Container6RLptQf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckRouteAccessService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Install\Service\Cli\Steps\CheckRouteAccess' autowired service.
     *
     * @return \App\Install\Service\Cli\Steps\CheckRouteAccess
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Engine/Model/ProcessStepInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Install/Service/Cli/CliStepInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Engine/Model/ProcessStepTrait.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Install/Service/Cli/CliStepTrait.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Install/Service/Cli/Steps/CheckRouteAccess.php';

        $container->factories['service_container']['App\\Install\\Service\\Cli\\Steps\\CheckRouteAccess'] = function () use ($container) {
            return new \App\Install\Service\Cli\Steps\CheckRouteAccess(($container->privates['App\\Install\\LegacyHandler\\InstallHandler'] ?? $container->getInstallHandlerService()));
        };

        return $container->factories['service_container']['App\\Install\\Service\\Cli\\Steps\\CheckRouteAccess']();
    }
}
