<?php

namespace Container6RLptQf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModuleMetadataProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Metadata\Service\ModuleMetadataProvider' shared autowired service.
     *
     * @return \App\Metadata\Service\ModuleMetadataProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 3).'/core/backend/Metadata/Service/ModuleMetadataProviderInterface.php';
        include_once \dirname(__DIR__, 3).'/core/backend/Metadata/Service/ModuleMetadataProvider.php';

        return $container->privates['App\\Metadata\\Service\\ModuleMetadataProvider'] = new \App\Metadata\Service\ModuleMetadataProvider(($container->privates['App\\Module\\LegacyHandler\\ModuleNameMapperHandler'] ?? $container->getModuleNameMapperHandlerService()), ($container->privates['App\\ViewDefinitions\\LegacyHandler\\ViewDefinitionsHandler'] ?? $container->load('getViewDefinitionsHandlerService')), ($container->privates['App\\Module\\LegacyHandler\\RecentlyViewed\\RecentlyViewedHandler'] ?? $container->load('getRecentlyViewedHandlerService')), ($container->privates['App\\Module\\LegacyHandler\\Favorites\\FavoritesHandler'] ?? $container->load('getFavoritesHandlerService')), ($container->services['cache.app'] ?? $container->getCache_AppService()));
    }
}
