<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPGwDxue\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPGwDxue/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPGwDxue.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPGwDxue\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPGwDxue\App_KernelDevDebugContainer([
    'container.build_hash' => 'PGwDxue',
    'container.build_id' => 'bf1f186f',
    'container.build_time' => 1719550586,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPGwDxue');
