<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6RLptQf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6RLptQf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6RLptQf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6RLptQf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6RLptQf\App_KernelDevDebugContainer([
    'container.build_hash' => '6RLptQf',
    'container.build_id' => 'cb3782fe',
    'container.build_time' => 1719470955,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6RLptQf');
